# credit https://medium.com/better-programming/deploy-your-gatsby-site-with-github-actions-e761ea93813f
# https://github.com/enriikke/gatsby-gh-pages-action/blob/main/README.md
name: Gatsby Publish

on:
  push:
    branches:
      develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
